import Head from "next/head";
import HeroSection from "../components/HeroSection";
import Layout from "../components/Layout";
import BestPackages from "../components/BestPackages";
import Island from "../components/Island";
import ContactCard from "../components/ContactCard";
import ClientSays from "../components/ClientSays";
import DiscoverButton from "../components/DiscoverButton";

export default function Home() {
  return (
    <Layout >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center max-w-7xl mx-auto">

      <HeroSection />

      {/* Best packages */}
      <BestPackages />
      
     {/* Discover Button */}
     <DiscoverButton />

      {/* Island */}
      <Island />

      {/* Contact Card */}
      <ContactCard />

      {/* What Our Clients Says  */}
      <ClientSays />
      </div>
    </Layout>
  );
}
