import Head from "next/head";
import HeroSection from "../components/HeroSection";
import Layout from "../components/Layout";
import BestPackages from "../components/BestPackages";
import Island from "../components/Island";
import ContactCard from "../components/ContactCard";
import ClientSays from "../components/ClientSays";
import DiscoverButton from "../components/DiscoverButton";

import { sanityClient, urlFor } from '../sanity';

export default function Home(collections) {
  return (
    <Layout >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center max-w-7xl mx-auto">

      <HeroSection />

      {/* Best packages */}
      {
        collections ? <BestPackages {...collections} /> : <h1>Loading...</h1>
      }
      
      
     {/* Discover Button */}
     <DiscoverButton />

      {/* Island */}
      <Island />

      {/* Contact Card */}
      <ContactCard />

      {/* What Our Clients Says  */}
      <ClientSays />
      </div>
    </Layout>
  );
};

export const getServerSideProps = async () => {
  const query = `*[_type == "packages"]{
    _id,
    place,
    amount,
    rating,
    categories,
    publishedAt,
    description,
    mainImage{
    asset,
  },
  previewImage{
    asset
  },
  category-> {
    _id,
    title,
    description,
  },
  }`

  const collections = await sanityClient.fetch(query);
  console.log(collections);

  return {
    props: {
      collections
    }
  }
   
};




