import Head from "next/head";
import HeroSection from "../components/HeroSection";
import IslandStays from "../components/IslandStays";
import NavBar from "../components/NavBar";
import PackagesCards from "../components/PackagesCards";

export default function Home() {
  return (
    <main className="relative z-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gradient-to-b from-[#c4ebf7] h-[100vh] opacity-80-100 to-[#FFFF]/10">
        <NavBar />
        <HeroSection />

        {/* Best packages */}
        <div className="flex flex-col items-center justify-center mx-auto">
          <h1 className="text-xl md:text-2xl font-semibold text-[#3A3A3A]">
            Best Packages For You
          </h1>
          <h3 className="text-sm font-sans text-[#5A5A5A]">
            This is a unique experience on ship, sea and land, exploring
            different coral islands of Lakshadweep.
          </h3>
        </div>

        <div className="flex space-x-10 m-10 items-center justify-center mx-auto">
          <PackagesCards />
          <PackagesCards />
          <PackagesCards />
        </div>

        <div className="flex justify-center items-center mx-auto">
          <button className="px-8 mt-10 md:px-5 py-3 rounded-md font-semibold border-2 text-base text-[#3282AD] border-[#3282AD]">
            Discover More
          </button>
        </div>

        {/* Island */}
        <div className="flex flex-col items-center justify-center mx-auto mt-10">
          <h1 className="text-xl md:text-2xl font-semibold text-[#3A3A3A]">
            Island Stays
          </h1>
          <h3 className="text-sm font-sans text-[#5A5A5A] mx-20">
            One can choose from a variety of beautiful coral islands which
            offers different staying experiences from thatched huts to luxurious
            modern properties. Every island offers a wider range of water sports
            and beach activities for you to enjoy.
          </h3>
        </div>

        <div className="grid grid-cols-3 w-fit mx-auto gap-x-10 gap-y-10 mt-10">
          <IslandStays />
          <IslandStays />
          <IslandStays />
          <IslandStays />
          <IslandStays />
          <IslandStays />
        </div>

        {/* Contact Card */}
        <div className="mt-10 max-w-fit mx-auto h-[261px] bg-[#42A7C3] flex items-center justify-between p-10 rounded-md">
          <div className="flex flex-col gap-5 text-white">
            <h1 className="text-white text-4xl font-bold">
              Let’s Ready to Explore The World With Us.
            </h1>
            <h2 className="">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Pellentesque efficitur ac quam in congue.{" "}
            </h2>
          </div>
          <img className="relative w-[453px] h-[189px] bg-cover" src="/map2.png" alt="" />
          <button className="px-6 md:px-8 py-3 rounded-md bg-white text-black inline">Contact Us</button>
        </div>


        {/* What Our Clients Says  */}

        <h1 className="text-xl mx-auto md:text-2xl font-semibold text-[#3A3A3A]">
        What Our Clients Says
          </h1>
      </div>
    </main>
  );
}
